---
- name: define nginx user
  set_fact:
    nginx_user: "{{ nginx_user }}"
  when: nginx_user is not defined

- name: update package control
  apt:
    update-cache: yes
- name: install nginx
  apt:
    name: nginx
    state: latest
- name: start nginx service
  service:
    name: nginx
    state: started
    enabled: true