---
- name: define nginx user
  set_fact:
    nginx_user: "{{ nginx_user }}"
  when: nginx_user is not defined

# install nginx
- include_tasks: Ubuntu-nginx.yml

- name: start nginx service
  service:
    name: nginx
    state: started
    enabled: true