---
- name: define nginx user
  set_fact:
    nginx_user: "{{ nginx_user }}"
- name: update package control
  apt:
    update-cache: yes
- name: install nginx
  apt:
    name: nginx
    state: latest
- name: start nginx
  service: 
    name: nginx
    state: started
- name: install php